### ISSUE TITLE
Data unavailable!

### ISSUE THREAD

**Issue by TrofimovAssya** [PaccMann/TITAN#1]
Hi!
I am trying to use your model - however when I attempt to use the "fine-tuning model", it requires the training data
Upon clicking on the data link in the README I got this:

![image](https://user-images.githubusercontent.com/7612410/119041715-f5777380-b984-11eb-998b-caa3cfb321e6.png)

Would it be possible to get another link?

Thanks in advance!

**Comment by jannisborn** [comment]
Hi @TrofimovAssya,

Thanks a lot for your interest in our work. Please use the following link to access the dataset and the splits: https://ibm.box.com/v/titan-dataset

We will update the repo shortly. Hope this helps!
Please feel free to reopen if applicable.

Best
Jannis
