### ISSUE TITLE
Running/ training on own dataset

### ISSUE THREAD

**Issue by cirdeCyL** [PaccMann/TITAN#11]
Hi Team,

so I have a dataset with training and test example, and I want to check out your model.
What and how shall I approach this?
Shall I still going for the sewmifrozen model and train it or shall I train it from scratch?

I am grateful if you can some instructions tips for how to do it.

Best cheers,
Cedric

**Comment by jannisborn** [comment]
Hi Cedric,
thanks for the interest in our work.  It depends on what you want to achieve so I cant formulate an interesting research question for you from the far.
It depends a bit on the statistics and size of the dataset but probably I would first predict the test data with the semifrozen model (zero-shot setting) and then finetune the pretrained semifrozen model on the train data and re-evaluate it on the test.
Hope this helps!

**Comment by cirdeCyL** [comment]
HI thanks for replying.
So I did as the readme suggested and start directly with the finetuning.
But I get a lot of errors, which seem to be connected to smiles embedding
![image](https://user-images.githubusercontent.com/96335168/172170537-da70ce0e-7fe0-4779-840a-435d14219937.png)

**Comment by jannisborn** [comment]
You're feeding amino acid sequences where there should be SMILES sequences. Please read the docs and compare your input files to the example inputs

**Comment by cirdeCyL** [comment]
Ok, I thought that you can also provide .csv files with the amino acids, because it is also like that in ./scripts/flexible_training.py
I'll transform my data into smile and try to run it again.
Thanks for your help and patience.
