### ISSUE TITLE
Ligand with MHC

### ISSUE THREAD

**Issue by KiAkize** [PaccMann/TITAN#13]
Hi,

First thank you for compiling and providing a benchmark 10-CV dataset. 
The MHC molecular information is also important during the binding of the pMHC complex to the TCR.
Could you please provide additional information on the MHC-I molecules (`HLA-X*XX:XX`, e.g. `HLA-A*02:01`) corresponding to each data (epitope-tcr)?

Thanks

**Comment by jannisborn** [comment]
Hi @KiAkize,
thanks for the interest and sorry for the late reply.

We did not compile the datasets used in our paper ourselves but rely on the VDJ and the ImmuneCODE database (see the references in our paper). You could ask the original data curators. But I recommend to you to have a look at their published raw data, you might find information that helps you extracting this information.
