### ISSUE TITLE
How do you visualize the epitope peptides based on the attention scores?

### ISSUE THREAD

**Issue by xpgege** [PaccMann/TITAN#14]
Hi! I am very interested in your article “TITAN: T-cell receptor specificity prediction with bimodal attention networks”  .  In the article fig4 c, I wonder which tools I  can use to visualize the epitope peptides based on the attention scores.

**Comment by jannisborn** [comment]
Hi @xpgege,

Thanks for your interest in the work. I suggest you to please have a look at this jupyter notebook: https://github.com/PaccMann/toxsmi/blob/master/notebooks/toxicity_attention_plot.ipynb

This shows you even how to make an interactive scatterplot of these molecules. If you find it useful please also consider citing the paper linked in the [README of the toxsmi repo](https://github.com/PaccMann/toxsmi#citation)

I hope this helps, let us know if you need anything else.
