### ISSUE TITLE
Bindingdb dataset

### ISSUE THREAD

**Issue by xpgege** [PaccMann/TITAN#15]
As I was reviewing the project, I noticed that you have provided access to the code and VDJdb dataset. However, the Bindingdb data was not included. Would it be possible for you to share this processed Bindingdb dataset with me

**Comment by jannisborn** [comment]
Hi @xpgege,

Please have a look at this repo https://github.com/PaccMann/paccmann_kinase_binding_residues and the corresponding papers (https://pubs.acs.org/doi/full/10.1021/acs.jcim.1c00889 and https://pubs.acs.org/doi/full/10.1021/acs.jcim.2c00840).
We're working on BindingDB there as well, using the same backbone that makes up TITAN. If you carefully read the README you will find a Box link which contains a folder called `pretraining` with the BindingDB data.

Hope this helps
