### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by andreas-wilm** [PaccMann/TITAN#16]
Hi there,

Many thanks for developing TITAN and making it public!

This sounds very interesting and I would like to give it a go, but already fail to use the provided test data. Specifically, I'm looking at [Run trained TITAN model on data section](https://github.com/PaccMann/TITAN#run-trained-titan-model-on-data), which I've translated to:

```
python3 scripts/flexible_model_eval.py \
    tutorial/data/test_small.csv \
    tutorial/data/tcr_full.csv \
    tutorial/data/epitopes.csv \
    ../TITAN-dataset/trained_model/ \
    bimodal_mca test20230303
```

I'm unsure about `./TITAN-dataset/trained_model/`, which points to the externally provided data (https://ibm.box.com/v/titan-dataset ). But I couldn't find a model in the repo providing the code. Anyway, the above fails with:
```
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [128, 1, 500, 26, 32]
```

Would it be possible to expand the documentation sections on to show how to use https://ibm.box.com/v/titan-dataset? 

Many thanks,
Andreas

**Comment by annaweber209** [comment]
Hi Andreas!
I think the issue might be that you are using the provided trained version of TITAN, which expects the epitopes to be in SMILES format - but you are giving it the epitopes.csv file, which contains the epitopes in amino acids. Try with the epitopes.smi file and it should work. Let me know if you encounter any further problems!
Best,
Anna

**Comment by annaweber209** [comment]
In the Box folder you will also find another, much smaller trained TITAN model, which is great for testing the setup as it doesn't take as much memory and time. You find it under tutorial/TITAN_small. It also expects smiles as an input. You can also run the tutorial.ipynb notebook to evaluate it and see if everything works! This also provides some code to directly visualise the attention on the input.

**Comment by andreas-wilm** [comment]
Thanks Anna!
