### ISSUE TITLE
shared dataset cannot be access

### ISSUE THREAD

**Issue by dukekuang** [PaccMann/TITAN#17]
Hi 

i would like run experiments with the shared data. The box link in below is not valid anymore. 

https://ibm.box.com/v/titan-dataset 

Could you reshare the data with us again? 

Thank you

**Comment by raghvendra5688** [comment]
Hi

i would like run experiments with the shared data. The box link in below is not valid anymore.

https://ibm.box.com/v/titan-dataset

Could you reshare the data with us again?

Thank you

**Comment by yanpinlu** [comment]
Hi

i would like run experiments with the shared data. The box link in below is not valid anymore.

https://ibm.box.com/v/titan-dataset

Could you reshare the data with us again?

Thank you @jannisborn @ndeutschmann

**Comment by jannisborn** [comment]
Please recheck the link, it should be functional again now :)
