### ISSUE TITLE
how did you get the tcr_full from VDJdb?

### ISSUE THREAD

**Issue by manna527** [PaccMann/TITAN#4]

**Comment by jannisborn** [comment]
Hi @manna527, thanks for the interest in our work and sorry for the delay.
I think @annaweber209 had a script to do this?

**Comment by annaweber209** [comment]
Hi @manna527 I just pushed the script. You still need to download the files linking V and J segment names to sequences from IMGT: https://www.imgt.org/vquest/refseqh.html
